//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Borrowings = new HashSet<Borrowing>();
        }
        
        public int Id { get; set; }

        [Display(Name = "Naziv knjige")]
        public string Title { get; set; }

        [Display(Name = "Pisac")]
        public string Writer { get; set; }

        [Display(Name = "Kategorija")]
        public int CategoryId { get; set; }

        [Display(Name = "Kategorija")]
        public string CategoryName { get; set; }

        [Display(Name = "Dostupnost")]
        public int StatusId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowing> Borrowings { get; set; }
    }
}
